apiVersion: v1
kind: Service
metadata:
  name: doc-custom-frontend-service
  namespace: doc-custom
spec:
  type: NodePort
  selector:
    app: doc-custom-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001
