export const DEFAULT_SYSTEM_SETTINGS = [
  "email-from",
  "email-from-nome",
  "email-copia",
  "sendgrid-api-key",
  "template-email-assunto",
  "template-email-corpo",
  "template-fatura",
  "omie-etapa-gerar",
  "omie-etapa-processado",
  "omie-etapa-erro",
  "omie-adiantamento-gerar",
  "omie-adiantamento-conta-corrente",
  "omie-adiantamento-categoria",
];
